! ============================================
! B-ASBR2  (AS 65002)  SR Node SID: 17011
! Loopback: 10.0.2.252/32
! eBGP peer: A-ASBR2 (10.100.12.5) AS 65001
! ============================================
frr version 10.5
frr defaults traditional
hostname b-asbr2
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config

interface lo
 ip address 10.0.2.252/32
 ip router isis CORE
 isis passive
!
interface b_asbr2-eth0
 description link-to-b_r1
 ip address 10.2.1.14/30
 ip router isis CORE
 isis network point-to-point
 isis hello-interval 3
 isis metric 10
 mpls enable
!
interface b_asbr2-eth1
 description eBGP-to-a_asbr2
 ip address 10.100.12.6/30
 mpls enable
!

route-map ALLOW-ALL permit 10
!

router isis CORE
 net 49.0002.0100.0002.0252.00
 is-type level-2-only
 topology ipv4-unicast
 segment-routing on
 segment-routing global-block 17000 17999
 segment-routing node-msd 8
 segment-routing prefix 10.0.2.252/32 index 11
 redistribute ipv4 bgp level-2 route-map ALLOW-ALL
!

router bgp 65002
 bgp router-id 10.0.2.252
 bgp log-neighbor-changes
 no bgp default ipv4-unicast
 !
 neighbor 10.100.12.5 remote-as 65001
 neighbor 10.100.12.5 description eBGP-to-A-ASBR2
 neighbor 10.100.12.5 ebgp-multihop 2
 neighbor 10.100.12.5 timers 10 30
 !
 address-family ipv4 unicast
  neighbor 10.100.12.5 activate
  neighbor 10.100.12.5 soft-reconfiguration inbound
  neighbor 10.100.12.5 route-map ALLOW-ALL in
  neighbor 10.100.12.5 route-map ALLOW-ALL out
  redistribute isis route-map ALLOW-ALL
  redistribute connected route-map ALLOW-ALL
  network 10.0.2.0/24
 exit-address-family
 !
 address-family link-state
  neighbor 10.100.12.5 activate
 exit-address-family
!
