! ============================================
! B-R3  (AS 65002)  SR Node SID: 17003
! Loopback: 10.0.2.3/32
! ============================================
frr version 10.5
frr defaults traditional
hostname b-r3
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config

interface lo
 ip address 10.0.2.3/32
 ip router isis CORE
 isis passive
!
interface b_r3-eth0
 description link-to-b_r2
 ip address 10.2.1.6/30
 ip router isis CORE
 isis network point-to-point
 isis hello-interval 3
 isis metric 10
 mpls enable
!
interface b_r3-eth1
 description link-to-b_asbr3
 ip address 10.2.1.17/30
 ip router isis CORE
 isis network point-to-point
 isis hello-interval 3
 isis metric 10
 mpls enable
!
interface b_r3-eth2
 description link-to-b_asbr4
 ip address 10.2.1.21/30
 ip router isis CORE
 isis network point-to-point
 isis hello-interval 3
 isis metric 10
 mpls enable
!

router isis CORE
 net 49.0002.0100.0002.0003.00
 is-type level-2-only
 topology ipv4-unicast
 segment-routing on
 segment-routing global-block 17000 17999
 segment-routing node-msd 8
 segment-routing prefix 10.0.2.3/32 index 3
!
