! ============================================
! B-R1  (AS 65002)  SR Node SID: 17001
! Loopback: 10.0.2.1/32
! ============================================
frr version 10.5
frr defaults traditional
hostname b-r1
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config

interface lo
 ip address 10.0.2.1/32
 ip router isis CORE
 isis passive
!
interface b_r1-eth0
 description link-to-b_r2
 ip address 10.2.1.1/30
 ip router isis CORE
 isis network point-to-point
 isis hello-interval 3
 isis metric 10
 mpls enable
!
interface b_r1-eth1
 description link-to-b_asbr1
 ip address 10.2.1.9/30
 ip router isis CORE
 isis network point-to-point
 isis hello-interval 3
 isis metric 10
 mpls enable
!
interface b_r1-eth2
 description link-to-b_asbr2
 ip address 10.2.1.13/30
 ip router isis CORE
 isis network point-to-point
 isis hello-interval 3
 isis metric 10
 mpls enable
!
interface b_r1-eth3
 description link-to-b_r2-redundant
 ip address 10.2.1.26/30
 ip router isis CORE
 isis network point-to-point
 isis hello-interval 3
 isis metric 20
 mpls enable
!

router isis CORE
 net 49.0002.0100.0002.0001.00
 is-type level-2-only
 topology ipv4-unicast
 segment-routing on
 segment-routing global-block 17000 17999
 segment-routing node-msd 8
 segment-routing prefix 10.0.2.1/32 index 1
!
