! ============================================
! C-R1  (AS 65003)  SR Node SID: 18002
! Loopback: 10.0.3.2/32
! ============================================
frr version 10.5
frr defaults traditional
hostname c-r1
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config

interface lo
 ip address 10.0.3.2/32
 ip router isis CORE
 isis passive
!
interface c_r1-eth0
 description link-to-c_pe1
 ip address 10.3.1.2/30
 ip router isis CORE
 isis network point-to-point
 isis hello-interval 3
 isis metric 10
 mpls enable
!
interface c_r1-eth1
 description link-to-c_asbr1
 ip address 10.3.1.9/30
 ip router isis CORE
 isis network point-to-point
 isis hello-interval 3
 isis metric 10
 mpls enable
!
interface c_r1-eth2
 description link-to-c_r2
 ip address 10.3.1.17/30
 ip router isis CORE
 isis network point-to-point
 isis hello-interval 3
 isis metric 10
 mpls enable
!

router isis CORE
 net 49.0003.0100.0003.0002.00
 is-type level-2-only
 topology ipv4-unicast
 segment-routing on
 segment-routing global-block 18000 18999
 segment-routing node-msd 8
 segment-routing prefix 10.0.3.2/32 index 2
!
