! ============================================
! C-ASBR2  (AS 65003)  SR Node SID: 18011
! Loopback: 10.0.3.253/32
! eBGP peer: B-ASBR4 (10.100.23.5) AS 65002
! ============================================
frr version 10.5
frr defaults traditional
hostname c-asbr2
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config

interface lo
 ip address 10.0.3.253/32
 ip router isis CORE
 isis passive
!
interface c_asbr2-eth0
 description link-to-c_r2
 ip address 10.3.1.14/30
 ip router isis CORE
 isis network point-to-point
 isis hello-interval 3
 isis metric 10
 mpls enable
!
interface c_asbr2-eth1
 description eBGP-to-b_asbr4
 ip address 10.100.23.6/30
 mpls enable
!

router isis CORE
 net 49.0003.0100.0003.0253.00
 is-type level-2-only
 topology ipv4-unicast
 segment-routing on
 segment-routing global-block 18000 18999
 segment-routing node-msd 8
 segment-routing prefix 10.0.3.253/32 index 11
!

router bgp 65003
 bgp router-id 10.0.3.253
 bgp log-neighbor-changes
 no bgp default ipv4-unicast
 !
 neighbor 10.100.23.5 remote-as 65002
 neighbor 10.100.23.5 description eBGP-to-B-ASBR4
 neighbor 10.100.23.5 ebgp-multihop 2
 neighbor 10.100.23.5 timers 10 30
 !
 address-family ipv4 unicast
  neighbor 10.100.23.5 activate
  neighbor 10.100.23.5 soft-reconfiguration inbound
  redistribute isis
  redistribute connected
  network 10.0.3.0/24
 exit-address-family
 !
 address-family link-state
  neighbor 10.100.23.5 activate
 exit-address-family
!
