! ============================================
! A-R2  (AS 65001)  SR Node SID: 16003
! Loopback: 10.0.1.3/32
! ============================================
frr version 10.5
frr defaults traditional
hostname a-r2
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config

interface lo
 ip address 10.0.1.3/32
 ip router isis CORE
 isis passive
!
interface a_r2-eth0
 description link-to-a_pe1
 ip address 10.1.1.6/30
 ip router isis CORE
 isis network point-to-point
 isis hello-interval 3
 isis metric 10
 mpls enable
!
interface a_r2-eth1
 description link-to-a_asbr2
 ip address 10.1.1.13/30
 ip router isis CORE
 isis network point-to-point
 isis hello-interval 3
 isis metric 10
 mpls enable
!
interface a_r2-eth2
 description link-to-a_r1
 ip address 10.1.1.18/30
 ip router isis CORE
 isis network point-to-point
 isis hello-interval 3
 isis metric 10
 mpls enable
!

router isis CORE
 net 49.0001.0100.0001.0003.00
 is-type level-2-only
 topology ipv4-unicast
 segment-routing on
 segment-routing global-block 16000 16999
 segment-routing node-msd 8
 segment-routing prefix 10.0.1.3/32 index 3
!
