! ============================================
! A-PE1  (AS 65001)  SR Node SID: 16001
! Loopback: 10.0.1.1/32
! ============================================
frr version 10.5
frr defaults traditional
hostname a-pe1
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config

! ── Interfaces ──────────────────────────────
interface lo
 ip address 10.0.1.1/32
 ip router isis CORE
 isis passive
!
interface a_pe1-eth0
 description link-to-a_r1
 ip address 10.1.1.1/30
 ip router isis CORE
 isis network point-to-point
 isis hello-interval 3
 isis metric 10
 mpls enable
!
interface a_pe1-eth1
 description link-to-a_r2
 ip address 10.1.1.5/30
 ip router isis CORE
 isis network point-to-point
 isis hello-interval 3
 isis metric 10
 mpls enable
!

! ── IS-IS ───────────────────────────────────
router isis CORE
 net 49.0001.0100.0001.0001.00
 is-type level-2-only
 topology ipv4-unicast
 !
 segment-routing on
 segment-routing global-block 16000 16999
 segment-routing node-msd 8
 !
 segment-routing prefix 10.0.1.1/32 index 1
!
