! ============================================
! A-ASBR2  (AS 65001)  SR Node SID: 16011
! Loopback: 10.0.1.253/32
! eBGP peer: B-ASBR2 (10.100.12.6) AS 65002
! ============================================
frr version 10.5
frr defaults traditional
hostname a-asbr2
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config

interface lo
 ip address 10.0.1.253/32
 ip router isis CORE
 isis passive
!
interface a_asbr2-eth0
 description link-to-a_r2
 ip address 10.1.1.14/30
 ip router isis CORE
 isis network point-to-point
 isis hello-interval 3
 isis metric 10
 mpls enable
!
interface a_asbr2-eth1
 description eBGP-to-b_asbr2
 ip address 10.100.12.5/30
 mpls enable
!

router isis CORE
 net 49.0001.0100.0001.0253.00
 is-type level-2-only
 topology ipv4-unicast
 segment-routing on
 segment-routing global-block 16000 16999
 segment-routing node-msd 8
 segment-routing prefix 10.0.1.253/32 index 11
!

router bgp 65001
 bgp router-id 10.0.1.253
 bgp log-neighbor-changes
 no bgp default ipv4-unicast
 !
 neighbor 10.100.12.6 remote-as 65002
 neighbor 10.100.12.6 description eBGP-to-B-ASBR2
 neighbor 10.100.12.6 ebgp-multihop 2
 neighbor 10.100.12.6 timers 10 30
 !
 address-family ipv4 unicast
  neighbor 10.100.12.6 activate
  neighbor 10.100.12.6 soft-reconfiguration inbound
  redistribute isis
  redistribute connected
  network 10.0.1.0/24
 exit-address-family
 !
 address-family link-state
  neighbor 10.100.12.6 activate
 exit-address-family
!
