! ============================================
! B-ASBR3  (AS 65002)  SR Node SID: 17012
! Loopback: 10.0.2.253/32
! eBGP peer: C-ASBR1 (10.100.23.2) AS 65003
! ============================================
frr version 10.5
frr defaults traditional
hostname b-asbr3
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config

interface lo
 ip address 10.0.2.253/32
 ip router isis CORE
 isis passive
!
interface b_asbr3-eth0
 description link-to-b_r3
 ip address 10.2.1.18/30
 ip router isis CORE
 isis network point-to-point
 isis hello-interval 3
 isis metric 10
 mpls enable
!
interface b_asbr3-eth1
 description eBGP-to-c_asbr1
 ip address 10.100.23.1/30
 mpls enable
!

router isis CORE
 net 49.0002.0100.0002.0253.00
 is-type level-2-only
 topology ipv4-unicast
 segment-routing on
 segment-routing global-block 17000 17999
 segment-routing node-msd 8
 segment-routing prefix 10.0.2.253/32 index 12
!

router bgp 65002
 bgp router-id 10.0.2.253
 bgp log-neighbor-changes
 no bgp default ipv4-unicast
 !
 neighbor 10.100.23.2 remote-as 65003
 neighbor 10.100.23.2 description eBGP-to-C-ASBR1
 neighbor 10.100.23.2 ebgp-multihop 2
 neighbor 10.100.23.2 timers 10 30
 !
 address-family ipv4 unicast
  neighbor 10.100.23.2 activate
  neighbor 10.100.23.2 soft-reconfiguration inbound
  redistribute isis
  redistribute connected
  network 10.0.2.0/24
 exit-address-family
 !
 address-family link-state
  neighbor 10.100.23.2 activate
 exit-address-family
!
