! ============================================
! A-R1  (AS 65001)  SR Node SID: 16002
! Loopback: 10.0.1.2/32
! ============================================
frr version 10.5
frr defaults traditional
hostname a-r1
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config

! ── Interfaces ──────────────────────────────
interface lo
 ip address 10.0.1.2/32
 ip router isis CORE
 isis passive
!
interface a_r1-eth0
 description link-to-a_pe1
 ip address 10.1.1.2/30
 ip router isis CORE
 isis network point-to-point
 isis hello-interval 3
 isis metric 10
 mpls enable
!
interface a_r1-eth1
 description link-to-a_asbr1
 ip address 10.1.1.9/30
 ip router isis CORE
 isis network point-to-point
 isis hello-interval 3
 isis metric 10
 mpls enable
!
interface a_r1-eth2
 description link-to-a_r2
 ip address 10.1.1.17/30
 ip router isis CORE
 isis network point-to-point
 isis hello-interval 3
 isis metric 10
 mpls enable
!

! ── IS-IS ───────────────────────────────────
router isis CORE
 net 49.0001.0100.0001.0002.00
 is-type level-2-only
 topology ipv4-unicast
 !
 segment-routing on
 segment-routing global-block 16000 16999
 segment-routing node-msd 8
 !
 segment-routing prefix 10.0.1.2/32 index 2
!
